navis/io/swc_io.py
setup.py
tests/common.py
tests/conftest.py
tests/test_neurons.py

This started out as a pretty simple addition to make #10 easier but I rapidly got carried away.
The existing API is unchanged, but would now be a shim over a more rigid `SwcReader` object which has methods for each type of arbitrary object a SWC can be read from. Using these makes it much easier for the caller to reason about and type annotate what they're putting into and getting out of the reader, but maybe this is a personal reference. "Explicit is better than implicit" conflicts with duck typing at times!
Also broadened the SWC reading tests a little, moved them out of the package (I find this makes it easier to detect installation-related issues, and end users don't need the tests anyway), and made them more `pytest`-y. The "old" tests are still in the package, but also don't work by …

Read SWC file from buffer

---

navis/nbl/nblast_funcs.py
navis/nbl/synblast_funcs.py

Hi @schlegelp - I was hoping to allow passing the `smat` kwarg to `NBlaster` through the `nblast_allbyall` function.
Note: I saw #28 so let me know if there are any collisions there (possibly just the parameter would need to be copied over description it looked like). 
Let me know if this looks okay or if there's anything you'd want me to revise.

Allow passing `smat` kwarg through `nblast_allbyall`

---

navis/io/__init__.py
navis/io/nrrd_io.py
tests/conftest.py
tests/test_io.py

For VoxelNeurons.
Adds (stupid) test for reading and for round trip read-write-read.
Does this look like a worthwhile MVP for a writer here? Writing NRRD is one of the things CATMAID uses natverse for.

Basic io.write_nrrd implementation

---

.readthedocs.yaml
docs/requirements.txt
requirements.txt

This config should get RTD to install a rust compiler, which will allow ncollpyde to build from source if a wheel isn't available. Thanks to @messense for documenting this in maturin and contributing the config to ncollpyde itself!
Probably want to make sure this gets through the RTD sausage machine, does that happen for PRs? Looks like it needs to be enabled here https://docs.readthedocs.io/en/stable/pull-requests.html

Fix ncollpyde in readthedocs

---

navis/core/base.py
tests/test_neurons.py

`__deepcopy__` needed another argument, useful for recursive copies.
Added a test which failed before and now passes.
BaseNeuron.copy() also didn't have the deepcopy kwarg, now added and
made to do something.
Noticed by @swilson27.
As an afterthought, currently `.copy(deepcopy=False)` isn't quite as shallow as it could be, as each of the attributes are shallow copied rather than just added to the new object. I doubt it'll ever come up and it's probably safer to leave it as it is.

Fix deepcopy(my_base_neuron)

---

navis/conversion/converters.py

```vx = navis.voxelize(cs, pitch='0.4 microns', smooth=1, counts=True, bounds=np.array([[0.0,0.0,0.0],[263.6,515.6,152.4]]))```
Trying to match template space 264x516 microns (660x1290) 382 z slices
so need to take away 0.4 to allow for the 0 index but the rounding is taking me over so adding extra rows
So I suggest the /pitch first before rounding

Fix to prevent rounding with fraction voxels

---

navis/sampling/resampling.py

When resampling a tree neuron, a set was used to index into a dataframe,
which will not be supported in a future version.

Fix PendingDeprecationWarning around node remapping

---

.editorconfig
README.md
navis/nbl/smat.py
navis/plotting/k3d/conftest.py

This fixes a few failing tests, some of the louder typechecking noise in my env, and aims to make get a dev env setup a bit smoother.
- README: adapt dev instructions for zsh-like shells
- pytest: ignore submodule on missing k3d dep
- smat: fix non-match iterations
- smat: replace with valid type hint
- Add minimal editorconfig

Miscellaneous hackathon fixes

---

navis/models/network_models.py

This PR proposes 2 fixes:
1) Previously `TraversalModel` implementation didn't assign the `results` property, making `make_summary()` call impossible.
2) Making typing of a `run` output consistent as it actually returns DataFrame.

Fix in network traversal models

---

navis/core/skeleton.py
navis/graph/graph_utils.py
navis/morpho/manipulation.py
navis/morpho/subset.py

Some navis functions expect TreeNeurons to have a `tags` attribute, or at least check whether it exists, presumably to catch subclasses like CatmaidNeurons. This effectively blesses that tag representation, so we may as well include it in the base class. For me at least, it's convenient to be able to represent tags without needing the live-fetching elements from CatmaidNeurons, so this change adds `tags = None` to the TreeNeuron class definition, and has other functions check whether it's non-None before trying to read anything from it. Having an optional attribute for tags, rather than an empty dict, means you can distinguish between untagged neurons and neurons which happen to have 0 tags; but having a firm attribute in place for it makes type checkers more happy.

Add tags=None to TreeNeurons

---

navis/models/network_models.py
tests/test_models/test_network_models.py

- Fix Bayesian traversal choosing entirely the wrong edges as seed edges
(!)
- Fix Bayesian traversal summary values for nodes whose activation CMF
never reaches 1.
- Do not include disconnected nodes in Bayesian traversal summary.
- Make Bayesian traversal consistent with the sampling model.
- Test all of the above.

models: fix Bayesian traversal model and test

---

navis/interfaces/neuprint.py

The first commit allows the user to access single-resolution "legacy" precomputed meshes, but only if they pass `lod=None`.  Maybe you can suggest a friendlier implementation.
The second commit concerns selecting a URL from the neuroglancer segmentation `source`.  In our neuroglancer links, we sometimes list multiple sources for segment properties, in which case `source` is a list-of-dict.
These have gone through only minimal testing (by hand).  Hopefully I haven't broken anything.

neuprint: Two fixes

---

navis/plotting/plotly/graph_objs.py

Previously this would throw an `AttributeError` during plotly plotting in the `skeleton2plotly` method while trying to access non-existing `neuron.nodes`.
```
empty_skel = navis.TreeNeuron(None)
navis.plot3d(empty_skel)
```
This tiny fix now skips plotting this TreeNeuron.

Skip plotting empty TreeNeuron in plotly

---

.github/workflows/publish-to-pypi.yml
.github/workflows/test-install.yml
.github/workflows/test-package.yml
docs/source/whats_new.rst
setup.py

Updating the test matrix, we'll see what falls out...
Updates one-off workflows (e.g. deploy) to use 3.10, and updates the test matrix otherwise.
Also reformats some YAML, unfortunately.
- Python 3.8 is not yet EOL but has been dropped by numpy releases since Apr 2023
- 3.11 was released Oct 2022
- 3.12 was released Oct 2023

CI: Update python versions

---

navis/graph/graph_utils.py

The `classify_nodes` function is called at `TreeNeuron` initialisation. In master, this function uses the igraph (or networkx) representation of the neuron. Generating the graph for a skeleton comes at a sizeable overhead but it will be cached for future use.
This PR re-implements the `classify_nodes` function using pure pandas. It's overall as fast as the current graph-based function minus the overhead for the construction of the graph. In my hands this speeds up import of skeletons by 5-6X. 
Many workflows (e.g. making dotprops from skeletons) do not need the graph representation, so being able to skip it is advantageous. For workflows that do need the graph, we simply delay its generation but shouldn't loose performance.
Thoughts @clbarnes?

Proposal: delay graph generation for skeletons

---

navis/morpho/subset.py

This PR improves the `subset_neuron` function:
1. Now works with multiple neurons at a time (previously accepted only single neurons)
2. `subset` can now be a callable
3. Re-implements the `submesh` function to reduce memory footprint when subsetting meshes (addresses #154)

Improve subset neurons

---

docs/changelog.md
docs/examples/0_io/plot_00_io_skeletons.py
docs/examples/4_remote/plot_02_remote_microns.py
navis/io/base.py
navis/io/mesh_io.py
navis/io/nmx_io.py
navis/io/precomputed_io.py
navis/io/swc_io.py
navis/utils/misc.py

With this PR we can load neurons straight from FTP servers. For example:
```python
url = "ftp://download.brainlib.org:8811/biccn/zeng/pseq/morph/200526"
nl = navis.read_swc(url + "*_raw.swc", limit=20)
```
TODOs:

Read files from FTP server

---

.github/workflows/test-package.yml
navis/config.py
navis/morpho/mmetrics.py
navis/plotting/plot_utils.py
pytest.ini

This PR potentially improves the numpy>=2.0 compatibility
- I replaced two references to `np.float_` as a dtype (and the minimum numpy version 1.16 seems to support both)
- NEP51 changes the representation of scalars (e.g. `np.float64(1.074)`, which fails the doctest when compared to `1.074`). While numpy<2.0 is still an accepted dependency, I change the representation back to python scalars to pass the tests.
This problem came up in #175, but is a separate issue, hence the separate PR.

Fix numpy doctest

---

docs/examples/0_io/tutorial_io_00_skeletons.py
docs/examples/1_plotting/tutorial_plotting_06_cortex.py
navis/io/base.py
navis/io/swc_io.py

Addresses #173 by using archive file stream instead of random access when reading from tar archives.
Due to the way this is implemented now, we won't be using parallel processes (i.e. the `parallel` parameter is ignored). We could create chunks of files that are adjacent in the archive and split the chunks across multiple processes. However, that in turn would generate issues with the process bar. 
Ultimately, the file streaming seems to be very performant (possibly because we're not having to open/close individual files?) and I'm not too worried about performance. On my machine I can read the tar archive with 97k hemibrain skeletons in around 3 minutes which isn't too shabby.
In addition to the above this PR contains:
- making `read_swc` more robust against unexpected number of columns
- …

Improve reading from tar archives

---

navis/sampling/resampling.py
requirements.txt

This PR adds safeguards against overflows for functions that (potentially) increase the number of nodes in a neuron:
Edit 03/12:
On closer inspection, the only function where overflows are an actual problem is `navis.resample_skeleton` and that only because it tries to force the same datatypes as the input neuron. All other functions that add new nodes let pandas free rein which means data is typically upcast. 
With the current fix `navis.resample_skeleton` will try to downcast to the input neuron's data types but check node IDs for potential overflows - if there are, it will downcast to the smallest possible integer dtype. This could be a model for the other functions but I'm also worried that this may make the code more brittle (e.g. some edge case we hadn't considered). For most users …

Prevent overflows 
